//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MyBlog.Domain.Entities
{
    public partial class Category
    {
    
        public virtual int Id { get; set; }
    
        public virtual string Name { get; set; }
    
        public virtual int BlogId { get; set; }
    
    
        public virtual Blog Blog{ get; set; }
    }
}
