//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.EntityClient;
namespace MyBlog.Domain.Entities
{
    public partial class Entities : ObjectContext
    {
        public const string ConnectionString = "name=Entities";
        public const string ContainerName = "Entities";
    
        #region Constructors
    
        public Entities()
            : base(ConnectionString, ContainerName)
        {
            ContextOptions.LazyLoadingEnabled = true;
        }
    
        public Entities(string connectionString)
            : base(connectionString, ContainerName)
        {
            ContextOptions.LazyLoadingEnabled = true;
        }
    
        public Entities(EntityConnection connection)
            : base(connection, ContainerName)
        {
            ContextOptions.LazyLoadingEnabled = true;
        }
    
        #endregion
    
        #region ObjectSet Properties
    
        public virtual ObjectSet<Category> Categories
        {
            get { return _categories  ?? (_categories = CreateObjectSet<Category>("Categories")); }
        }
    
        private ObjectSet<Category> _categories;
    
        public virtual ObjectSet<Comment> Comments
        {
            get { return _comments  ?? (_comments = CreateObjectSet<Comment>("Comments")); }
        }
    
        private ObjectSet<Comment> _comments;
    
        public virtual ObjectSet<Post> Posts
        {
            get { return _posts  ?? (_posts = CreateObjectSet<Post>("Posts")); }
        }
    
        private ObjectSet<Post> _posts;
    
        public virtual ObjectSet<Blog> Blogs
        {
            get { return _blogs  ?? (_blogs = CreateObjectSet<Blog>("Blogs")); }
        }
    
        private ObjectSet<Blog> _blogs;

        #endregion
    }
}
