//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MyBlog.Domain.Entities
{
    public partial class Post
    {
    
        public virtual int Id { get; private set; }
    
        public virtual System.DateTime CreationDate { get; private set; }
    
        public virtual System.DateTime LastModifiedDate { get; private set; }
    
        public virtual Nullable<System.DateTime> PublishDate { get; private set; }
    
        public virtual string Subject { get; private set; }
    
        public virtual string Body { get; private set; }
    
        public virtual bool CommentsEnabled { get; private set; }
    
        public virtual int BlogId { get; private set; }
    
        public virtual IEnumerable<Comment> Comments{ get { return _comments; } }
        private List<Comment> _comments = new List<Comment>();
    
        public virtual IEnumerable<Category> Categories{ get { return _categories; } }
        private List<Category> _categories = new List<Category>();
    
    
        public virtual Blog Blog{ get; private set; }
    }
}
