//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

namespace MyBlog.Domain.Entities
{
    
    public partial class UserInfo
    {
        public string Name { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
    
    }
}
